# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TailJson < Formula
  desc ""
  homepage "https://github.com/mgreg90/homebrew-tail-json"
  version "1.0.0"

  depends_on "git"
  depends_on "go"
  depends_on "jq"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/mgreg90/homebrew-tail-json/releases/download/v1.0.0/tail-json_1.0.0_darwin_arm64.tar.gz"
      sha256 "85354f708c1bf1c016f0dacbcded39095241a7f09aa7099bec90ac569de027bf"

      def install
        bin.install "tail-json"
        bash_completion.install "completions/tail-json-cli.bash" => "tail-json"
        zsh_completion.install "completions/tail-json-cli.zsh" => "_tail-json"
        fish_completion.install "completions/tail-json-cli.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mgreg90/homebrew-tail-json/releases/download/v1.0.0/tail-json_1.0.0_darwin_amd64.tar.gz"
      sha256 "98b50b4aeaf54b881863f4c558a1c48cfdbb94485fdbfc665d9d157cf25a5d75"

      def install
        bin.install "tail-json"
        bash_completion.install "completions/tail-json-cli.bash" => "tail-json"
        zsh_completion.install "completions/tail-json-cli.zsh" => "_tail-json"
        fish_completion.install "completions/tail-json-cli.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/mgreg90/homebrew-tail-json/releases/download/v1.0.0/tail-json_1.0.0_linux_amd64.tar.gz"
      sha256 "3c378a33ed449d495e22e107419b0be155d5e2b7ebd6ea73ec79f2426a7a4cf2"

      def install
        bin.install "tail-json"
        bash_completion.install "completions/tail-json-cli.bash" => "tail-json"
        zsh_completion.install "completions/tail-json-cli.zsh" => "_tail-json"
        fish_completion.install "completions/tail-json-cli.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mgreg90/homebrew-tail-json/releases/download/v1.0.0/tail-json_1.0.0_linux_arm64.tar.gz"
      sha256 "32a86a32ca03873cad13108845ea989a18a7fae7af996c4eda6b0e8ec3812b88"

      def install
        bin.install "tail-json"
        bash_completion.install "completions/tail-json-cli.bash" => "tail-json"
        zsh_completion.install "completions/tail-json-cli.zsh" => "_tail-json"
        fish_completion.install "completions/tail-json-cli.fish"
      end
    end
  end
end
